version: "3.7"
services:

  restapi:
    container_name: ${PROJECT_NAME}-restapi
    image: ghcr.io/openimis/openimis-rest_api:develop
    volumes:
      - ./conf/restapi:/app/config
      - ./logs:/app/log
      - photos:/app/photo
    restart: always
    depends_on:  
      db:
        condition: service_healthy
    networks:
      openimis-net:

volumes:
  photos:
networks:
  openimis-net:
    name: ${PROJECT_NAME}-openimis-net
    external: True